version: '3.8'
name: flexjob

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - CONNECTION_STRING=Server=db;Port=3306;Database=flexjob;Uid=root;Pwd=rootpassword;

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: flexjob
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
